### ISSUE TITLE
Would prefer an example using react-router

### ISSUE THREAD

**Issue by super-cache-money** [mhart/react-server-routing-example#1]

**Comment by mhart** [comment]
The purpose of this repository is to show an example from the ground up, using no framework in particular so that you can understand the concepts without needing to understand yet another API.

react-router is just one routing framework you could choose if you like, and it has a very particular way of doing things, but there are plenty of others, [some react specific](http://strml.viewdocs.io/react-router-component), [others](https://github.com/flatiron/director) [not](http://visionmedia.github.io/page.js/). I'd encourage you to start without using one at all and see which patterns and directions you like.
